export * from './Navbar';
export * from './Home';
export * from './About';
export * from './Experience';
export * from './Loader';
export * from './Skills';
export * from './Degrees';
export * from './ContactModal';
export * from './Footer';